### ISSUE TITLE
Errors in emoncms.log

### ISSUE THREAD

**Issue by glynhudson** [emoncms/device#16]
Errors in emoncms.log related to device module from Dave's test emonPi: 

1 /var/www/emoncms/Modules/device/device_model.php(280): Device->init_template(7) #2 /var/www/emoncms/scripts/phpmqtt_input.php(257): Device->autocreate(1, 'smartplug', 'smartplug') #3 [internal function]: message(Object(Mosquitto\Message)) #4 /var/www/emoncms/scripts/phpmqtt_input.php(116): Mosquitto\Client->loop() #5 {main} 2018-01-24 11:53:00.826\|ERROR\|phpmqtt_input.php\|exception 'ErrorException' with message 'Missing argument 2 for Device::init_template(), called in /var/www/emoncms/Modules/device/device_model.php on line 280 and defined' in /var/www/emoncms/Modules/device/device_model.php:543 Stack trace: #0 /var/www/emoncms/Modules/device/device_model.php(543): exceptions_error_handler(2, 'Missing argumen...', '/var/www/emoncm...', 543, Array) #1 /var/www/emoncms/Modules/device/device_model.php(280): Device->init_template(7) #2 /var/www/emoncms/scripts/phpmqtt_input.php(257): Device->autocreate(1, 'smartplug', 'smartplug') #3 [internal function]: message(Object(Mosquitto\Message)) #4 /var/www/emoncms/scripts/phpmqtt_input.php(116): Mosquitto\Client->loop() #5 {main} 2018-01-24 21:54:50.805\|WARN\|phpmqtt_input.php\|Not connected, retrying connection 2018-01-24 21:54:50.831\|WARN\|phpmqtt_input.php\|Connecting to MQTT server: Connection Accepted.: code: 0 2018-01-24 22:17:35.137\|WARN\|phpmqtt_input.php\|Not connected, retrying connection 2018-01-24 22:17:35.191\|WARN\|phpmqtt_input.php\|Connecting to MQTT server: Connection Accepted.: code: 0 2018-01-31 05:47:43.418\|ERROR\|phpmqtt_input.php\|exception 'ErrorException' with message 'Missing argument 2 for Device::init_template(), called in /var/www/emoncms/Modules/device/device_model.php on line 267 and defined' in /var/www/emoncms/Modules/device/device_model.php:530 Stack trace: #0 /var/www/emoncms/Modules/device/device_model.php(530): exceptions_error_handler(2, 'Missing argumen...', '/var/www/emoncm...', 530, Array) #1 /var/www/emoncms/Modules/device/device_model.php(267): Device->init_template(7) #2 /var/www/emoncms/scripts/phpmqtt_input.php(257): Device->autocreate(1, 'smartplug', 'smartplug') #3 [internal function]: message(Object(Mosquitto\Message)) #4 /var/www/emoncms/scripts/phpmqtt_input.php(116): Mosquitto\Client->loop() #5 {main} | 1 /var/www/emoncms/Modules/device/device_model.php(280): Device->init_template(7) #2 /var/www/emoncms/scripts/phpmqtt_input.php(257): Device->autocreate(1, 'smartplug', 'smartplug') #3 [internal function]: message(Object(Mosquitto\Message)) #4 /var/www/emoncms/scripts/phpmqtt_input.php(116): Mosquitto\Client->loop() #5 {main} 2018-01-24 11:53:00.826\|ERROR\|phpmqtt_input.php\|exception 'ErrorException' with message 'Missing argument 2 for Device::init_template(), called in /var/www/emoncms/Modules/device/device_model.php on line 280 and defined' in /var/www/emoncms/Modules/device/device_model.php:543 Stack trace: #0 /var/www/emoncms/Modules/device/device_model.php(543): exceptions_error_handler(2, 'Missing argumen...', '/var/www/emoncm...', 543, Array) #1 /var/www/emoncms/Modules/device/device_model.php(280): Device->init_template(7) #2 /var/www/emoncms/scripts/phpmqtt_input.php(257): Device->autocreate(1, 'smartplug', 'smartplug') #3 [internal function]: message(Object(Mosquitto\Message)) #4 /var/www/emoncms/scripts/phpmqtt_input.php(116): Mosquitto\Client->loop() #5 {main} 2018-01-24 21:54:50.805\|WARN\|phpmqtt_input.php\|Not connected, retrying connection 2018-01-24 21:54:50.831\|WARN\|phpmqtt_input.php\|Connecting to MQTT server: Connection Accepted.: code: 0 2018-01-24 22:17:35.137\|WARN\|phpmqtt_input.php\|Not connected, retrying connection 2018-01-24 22:17:35.191\|WARN\|phpmqtt_input.php\|Connecting to MQTT server: Connection Accepted.: code: 0 2018-01-31 05:47:43.418\|ERROR\|phpmqtt_input.php\|exception 'ErrorException' with message 'Missing argument 2 for Device::init_template(), called in /var/www/emoncms/Modules/device/device_model.php on line 267 and defined' in /var/www/emoncms/Modules/device/device_model.php:530 Stack trace: #0 /var/www/emoncms/Modules/device/device_model.php(530): exceptions_error_handler(2, 'Missing argumen...', '/var/www/emoncm...', 530, Array) #1 /var/www/emoncms/Modules/device/device_model.php(267): Device->init_template(7) #2 /var/www/emoncms/scripts/phpmqtt_input.php(257): Device->autocreate(1, 'smartplug', 'smartplug') #3 [internal function]: message(Object(Mosquitto\Message)) #4 /var/www/emoncms/scripts/phpmqtt_input.php(116): Mosquitto\Client->loop() #5 {main}
-- | --
1 /var/www/emoncms/Modules/device/device_model.php(280): Device->init_template(7) #2 /var/www/emoncms/scripts/phpmqtt_input.php(257): Device->autocreate(1, 'smartplug', 'smartplug') #3 [internal function]: message(Object(Mosquitto\Message)) #4 /var/www/emoncms/scripts/phpmqtt_input.php(116): Mosquitto\Client->loop() #5 {main} 2018-01-24 11:53:00.826\|ERROR\|phpmqtt_input.php\|exception 'ErrorException' with message 'Missing argument 2 for Device::init_template(), called in /var/www/emoncms/Modules/device/device_model.php on line 280 and defined' in /var/www/emoncms/Modules/device/device_model.php:543 Stack trace: #0 /var/www/emoncms/Modules/device/device_model.php(543): exceptions_error_handler(2, 'Missing argumen...', '/var/www/emoncm...', 543, Array) #1 /var/www/emoncms/Modules/device/device_model.php(280): Device->init_template(7) #2 /var/www/emoncms/scripts/phpmqtt_input.php(257): Device->autocreate(1, 'smartplug', 'smartplug') #3 [internal function]: message(Object(Mosquitto\Message)) #4 /var/www/emoncms/scripts/phpmqtt_input.php(116): Mosquitto\Client->loop() #5 {main} 2018-01-24 21:54:50.805\|WARN\|phpmqtt_input.php\|Not connected, retrying connection 2018-01-24 21:54:50.831\|WARN\|phpmqtt_input.php\|Connecting to MQTT server: Connection Accepted.: code: 0 2018-01-24 22:17:35.137\|WARN\|phpmqtt_input.php\|Not connected, retrying connection 2018-01-24 22:17:35.191\|WARN\|phpmqtt_input.php\|Connecting to MQTT server: Connection Accepted.: code: 0 2018-01-31 05:47:43.418\|ERROR\|phpmqtt_input.php\|exception 'ErrorException' with message 'Missing argument 2 for Device::init_template(), called in /var/www/emoncms/Modules/device/device_model.php on line 267 and defined' in /var/www/emoncms/Modules/device/device_model.php:530 Stack trace: #0 /var/www/emoncms/Modules/device/device_model.php(530): exceptions_error_handler(2, 'Missing argumen...', '/var/www/emoncm...', 530, Array) #1 /var/www/emoncms/Modules/device/device_model.php(267): Device->init_template(7) #2 /var/www/emoncms/scripts/phpmqtt_input.php(257): Device->autocreate(1, 'smartplug', 'smartplug') #3 [internal function]: message(Object(Mosquitto\Message)) #4 /var/www/emoncms/scripts/phpmqtt_input.php(116): Mosquitto\Client->loop() #5 {main}

**Comment by TrystanLea** [comment]
This looks like the use of the device-integration branch of the device module without the use of the device-support branch of emoncms.
