### ISSUE TITLE
Template Caching

### ISSUE THREAD

**Issue by TrystanLea** [emoncms/device#20]
Device template cache needs reloading somehow so that users can see new devices, calling:

https://emoncms.org/device/template/reload.json

works, perhaps this could be called once when the device interface is loaded?

What do you think @adminde 

I've just updated the OpenEVSE device, but no one will be able to see it, in its new location on emoncms.org without calling https://emoncms.org/device/template/reload.json

**Comment by adminde** [comment]
Sorry for my late response

I actually removed that while updating the redis caching a while ago.
The template caching is user-independent. Hence on a asynchronous environment with several users like emoncms.org it would be completely unaccepptable to reload the template cache every time anyone loads the device view.

I just realized I never finished that thought 😉
... the best solution could potentially be to add a button in admin view for the device-support branch?
