### ISSUE TITLE
Question about device templates held in Redis

### ISSUE THREAD

**Issue by pb66** [emoncms/device#25]
Why does every template seem to have 2 superfluous key:value pairs?

Whilst trying to navigate the Redis entries for device templates (related to #24) I noticed that every template has the following 

```
1) "module"
2) "device"

. . . 

11) "control"
12) ""
```

fields 2 thru 10 seem valid enough, but these don't seem to serve an obvious purpose (that I can see)

```
pb66@test2:$ redis-cli HGETALL emoncms:device:template:emonpi-SPV1
 1) "module"
 2) "device"
 3) "name"
 4) "Solar PV Type 1"
 5) "category"
 6) "OpenEnergyMonitor"
 7) "group"
 8) "EmonPi"
 9) "description"
10) "EmonPi Solar PV Type 1 template"
11) "control"
12) ""
```

**Comment by adminde** [comment]
Hi @pb66,

the form of the dump irritates me quite a lot to be honest, though they appear to be pairs? 1) and 2) is probably a key value pair?
Main purpose of the "module" is to have the destiction between emoncms modules. E.g. my muc module has a muc_template.php file which will be used for "moduel":"muc".
12) being empty is strange though... "control" is just a boolean flag if the template contains a control section, defining if it should be listed in controllable devices in one of the OEM projects as far as I know. I introduced 2 other flags in my not-yet-pull-requested changes ([as shortly introduced in the Forum](https://community.openenergymonitor.org/t/development-devices-inputs-and-feeds-in-emoncms/4281/122)).
To my knowledge everything serves an important purpose 😄 and if not yet, it serves an important purpose for my future PR.
