### ISSUE TITLE
Unit selection box need to be larger

### ISSUE THREAD

**Issue by glynhudson** [emoncms/device#28]
![selection_015](https://user-images.githubusercontent.com/758844/47230226-8cd94c00-d3c1-11e8-9207-206c8bd8b4c5.jpg)
![selection_014](https://user-images.githubusercontent.com/758844/47230229-8d71e280-d3c1-11e8-9982-ec4192a75e32.jpg)

**Comment by emrysr** [comment]
the code to fix this was in the emoncms core feed view.

[firefox screenshot of units dropdown showing correctly]
![image](https://user-images.githubusercontent.com/1466013/47357528-d3c78a00-d6be-11e8-96e3-548797c33843.png)


https://github.com/emoncms/emoncms/pull/1080

**Comment by glynhudson** [comment]
Interesting just tested again ensured running latest master using Chrome 69.0.3497.120

![screenshot 2018-10-24 at 02 09 04](https://user-images.githubusercontent.com/758844/47399750-ef1fad00-d731-11e8-9caa-b3efbe6dfc0a.png)
![screenshot 2018-10-24 at 02 08 56](https://user-images.githubusercontent.com/758844/47399751-ef1fad00-d731-11e8-9d02-7ee9bedbbc5a.png)

Not a major issue, don't spend too much time on this!

**Comment by glynhudson** [comment]
Fixed by https://github.com/emoncms/emoncms/pull/1080
