### ISSUE TITLE
Custom and pre-defined template sets

### ISSUE THREAD

**Issue by pb66** [emoncms/device#5]
Could we consider having the `data` directory structure sub-divided rather than all the templates in one folder? 

That way users/we can better manage custom sets of templates that meet our own needs and standard templates can be grouped and maintained in their own repo's, eg OEM stuff in one repo, the existing "amig.json" and "amrm.json" etc in another so that we can install the templates we want and more importantly, maintain our own repo of custom templates without them having to share a folder with the included templates.

A similar sort of set up to the emoncms Modules folder where a minimum of just an "example" folder is included in the `emoncms/device` repo and a `.gitignore` file to prevent installed template folders from being committed when contributing.

The folder names could also double up as grouping names so that as the number of templates increases they are still easily found.

This might encourage other device/software developers to maintain their own device templates to make using their products even easier to use with emoncms.

I would be happy to look at this if it's an acceptable idea, I'm not specifically asking for someone to do it, just asking if anyone has any opinion at this stage

**Comment by TrystanLea** [comment]
This is now implemented
