### ISSUE TITLE
Processes only accessible via the depreciated mechanism 

### ISSUE THREAD

**Issue by pb66** [emoncms/device#6]
To make the templates easier to read I have tried using the function name in place of the processlist index number eg `"process":"log_to_feed"` rather than `"process":"1"` but that doesn't seem to work.

I have also tried `"process":"process__log_to_feed"` to try and match the `"process":"additionalp__andfunction"` which does work in the events module, so it appears to be that the original processes are only available via the numeric index that has apparently only been kept for backwards compatability, is that correct?

if so how difficult would it be to make them available via the function names?

**Comment by TrystanLea** [comment]
Good question, Im going to add a whole set of standard emontx, emonth and emonpi templates soon which will be a good chance to look into it.

**Comment by chaveiro** [comment]
The original way of identify a process was by a number, so, to maintain backward compatibility it has remained like that. 
Only the new processes have that textual identifiers.
Changing the original to a textual id, will require data repair on the database.

**Comment by TrystanLea** [comment]
This has since been implemented
